pipeline{
    
    agent any
    
    stages{
        stage("Build"){
            steps{
                echo("Build the project")
            }
        }
        
         stage("Run UT"){
            steps{
                echo("Run UTs")
            }
        }
         stage("Deploy to Dev"){
            steps{
                echo("Dev Env.")
            }
        }
         stage("Deploy to QA"){
            steps{
                echo("QA Env.")
            }
        }
         stage("Run Automation Reg. Test"){
            steps{
                echo("Run Automation Reg. Test")
            }
        }
         stage("Deploy to Stage Env."){
            steps{
                echo("Stage Env.")
            }
        }
         stage("Deploy to Prod Env."){
            steps{
                echo("Prod Env.")
            }
        }
    }
}